### PR TITLE
Add parsing functionality

### PR DESCRIPTION
**Pull request by mahahahad**

### CODE REVIEW

**Comment by Ali-Danish-72** [comment]
VS Code detected an unused variable in the function `parse_exec()`. I tried to see if there is any use for the variable `i`, and it seems to be really out of place... as in it not being of any use. I am not sure how the compiler hasn't caught it.

**Comment by mahahahad** [comment]
Yes, that was there because of the previous approach I was using and became redundant when I changed it and forgot to remove it.

**Comment by Ali-Danish-72** [comment]
About the multiple redirections, there is an error. The innermost redirection takes affect when it should be the outermost redirection, in terms of the structure you have.

case:
`echo hi > p > o > i > u > y`

expected output of `cat y`:
> hi

actual output:
>

**Review by Ali-Danish-72 — APPROVED** [review]
We'll go back to working on separate branches after this.

**Pull request merged**
