### PR TITLE
Added the minimal aspect of 2 of the builtins.

### PR DESCRIPTION
**Pull request by Ali-Danish-72**
Created the bare bones of `echo` and `env`. There are some important aspects of it that I added to the code as comments. Make sure you get an understanding of it.

### CODE REVIEW

**Comment by Ali-Danish-72** [comment]
I also wanna do something about the organization of these things. I have seen people use multiple folders and header files to have a well organized project.

**Comment by mahahahad** [comment]
> I also wanna do something about the organization of these things. I have seen people use multiple folders and header files to have a well organized project.

I thought you meant making a folder for the built-ins but you've already done that. Are you saying we should have a header file for the built-ins in that folder?

**Review by mahahahad — COMMENTED** [review]
Seems good

**Comment by Ali-Danish-72** [comment]
The purpose of this branch is simply to be able to work bit by bit on the builtins while the parsing gets ready as there will be a massive need for adaptation when that is done. As for the organization, that is something that just happens to be on my mind.

**Pull request merged**
